name: Java CI

on:
  push:
    branches:
    - master
    tags:
      - "v*.*"
  pull_request:
    branches:
    - master
    
jobs:
  create_release:
    name: "创建发布"
    needs: [build]
    if: startsWith(github.ref, 'refs/tags/v')

    runs-on: ubuntu-latest
    steps:
    - name: 下载构建
      uses: actions/download-artifact@v3.0.1
        
    - name: 创建发布
      uses: softprops/action-gh-release@v1
      with:
        draft: true
        fail_on_unmatched_files: true
        files: |
          artifacts/*
  build:
    if: startsWith(github.event.head_commit.message, '[CI skip]') == false
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3.2.0
    - name: Set up JDK 8.0.352+8
      uses: actions/setup-java@v3.9.0
      with:
        java-version: 8.0.352+8
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn package --file pom.xml
    - name: 自动释放
      if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
      uses: marvinpinto/action-automatic-releases@v1.2.1
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "jar"
        prerelease: true
        title: "MCUpgrades 自动构建版本"
        files: |
           target/*
    - name: 上传 The Bruh
      uses: actions/upload-artifact@v3
      with:
        name: artifacts
        path: |
           target/*.jar
